apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deployment
  labels:
    app: myjavaapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp
        image: 600735812827.dkr.ecr.us-west-1.amazonaws.com/javasession2:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-service
spec:
  selector:
    app.kubernetes.io/name: Myjavaapp
  ports:
    - protocol: http
      port: 80
      targetPort: 8080
    type: LoadBalancer